### ISSUE TITLE
install

### ISSUE THREAD

**Issue by mabitbol** [thibautlouis/toy_likelihood#9]
Hey, 

I am getting the following error finding the right directory. Maybe has to do with the install. I did pip install -e . 

Sorry for the dumb question!

$ python3 pslike/pslike.py -y global.yaml
Traceback (most recent call last):
  File "pslike/pslike.py", line 243, in <module>
    main()
  File "pslike/pslike.py", line 203, in main
    prepare_data(setup, args.sim_id)
  File "pslike/pslike.py", line 35, in prepare_data
    l, ps = likelihood_utils.read_spectra(file_name)
  File "/mnt/zfsusers/mabitbol/toy_likelihood/pslike/likelihood_utils.py", line 8, in read_spectra
    data=np.loadtxt(fname)
  File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 898, in loadtxt
    fh = iter(open(fname))
FileNotFoundError: [Errno 2] No such file or directory: 'like_products/Dl_LAT_93xLAT_93.dat'

**Comment by thibautlouis** [comment]
Hi Max, this is per design you need to specify the simulation number, for example -i 0, otherwise it will assume you run on data, cheers ! (we will document this)

**Comment by mabitbol** [comment]
Ok. Can you show me a simple example? I am just trying to test that it is installed correctly etc.

**Comment by mabitbol** [comment]
Ah nevermind. I forgot to type python3.... :)

**Comment by mabitbol** [comment]
Ah nevermind. I forgot to type python3.... :)
